/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./components/**/*.{js,ts,jsx,tsx}", "./app/**/*.{ts,tsx}"],
  theme: {
    fontFamily: {
      sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
      serif: ["var(--font-serif)", "ui-serif", "Georgia", "serif"],
      mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
    },
    // html font-size is 62.5%, so 1rem = 10px.
    fontSize: {
      xs: "1.2rem",
      sm: "1.4rem",
      md: "1.6rem",
      base: "1.6rem",
      lg: "1.8rem",
      xl: ["2.2rem", "1.3"],
      "2xl": "2.4rem",
      "3xl": "2.8rem",
      "4xl": ["3.4rem", "1.1"],
      "5xl": ["4.2rem", "1.05"],
      "6xl": ["5.2rem", "1"],
      "7xl": ["6.4rem", "1"],
      "8xl": ["8rem", "0.95"],
      "9xl": ["11rem", "0.9"],
      // Fluid display sizes for hero-scale typography.
      "display-sm": ["clamp(4rem, 7vw, 8rem)", "0.95"],
      display: ["clamp(5.2rem, 11vw, 17rem)", "0.88"],
      "display-xl": ["clamp(6rem, 17vw, 26rem)", "0.85"],
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: "#000",
      white: "#fff",
      ink: {
        DEFAULT: "#0A0A0B",
        50: "#141416",
        100: "#1B1B1E",
        200: "#26262A",
      },
      bone: {
        DEFAULT: "#EDEAE3",
        dim: "#B9B5AC",
      },
      ember: {
        DEFAULT: "#FF5A1F",
        soft: "#FF8A5C",
      },
      periwinkle: "#7C9CFF",
      lime: "#C9F24B",
      orchid: "#F4C8FF",
      line: "rgba(237, 234, 227, 0.1)",
      // Legacy token names kept so older pages pick up the new palette.
      "off-white": "#EDEAE3",
      "transparent-white": "rgba(237, 234, 227, 0.08)",
      background: "#0A0A0B",
      grey: "#8A8780",
      "grey-dark": "#1B1B1E",
      "primary-text": "#B9B5AC",
    },
    spacing: {
      0: "0",
      px: "1px",
      0.5: "0.2rem",
      1: "0.4rem",
      1.5: "0.6rem",
      2: "0.8rem",
      2.5: "1rem",
      3: "1.2rem",
      3.5: "1.4rem",
      4: "1.6rem",
      5: "2rem",
      6: "2.4rem",
      7: "2.8rem",
      8: "3.2rem",
      9: "3.6rem",
      10: "4rem",
      11: "4.4rem",
      12: "4.8rem",
      13: "5.2rem",
      14: "5.6rem",
      15: "6rem",
      16: "6.4rem",
      20: "8rem",
      24: "9.6rem",
      28: "11.2rem",
      32: "12.8rem",
      36: "14.4rem",
      40: "16rem",
      48: "19.2rem",
      "navigation-height": "var(--navigation-height)",
    },
    extend: {
      maxWidth: {
        site: "144rem",
      },
      backgroundImage: {
        "primary-gradient": "linear-gradient(100deg, #FF5A1F 0%, #FF8A5C 100%)",
        "page-gradient": "none",
        "glass-gradient":
          "linear-gradient(rgba(237,234,227,0.02) 0%, rgba(237,234,227,0.05) 100%)",
      },
      boxShadow: {
        primary: "0 0 40px rgba(255, 90, 31, 0.35)",
      },
      transitionTimingFunction: {
        expo: "cubic-bezier(0.16, 1, 0.3, 1)",
        quart: "cubic-bezier(0.76, 0, 0.24, 1)",
      },
      keyframes: {
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
        spin: {
          to: { transform: "rotate(360deg)" },
        },
        pulse: {
          "0%, 100%": { opacity: 1 },
          "50%": { opacity: 0.35 },
        },
      },
      animation: {
        "spin-slow": "spin 40s linear infinite",
        pulse: "pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
